"""fixes deleting users

Revision ID: 62bd53819d3e
Revises:
Create Date: 2025-09-02 20:11:22.157268

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62bd53819d3e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=False),
        sa.Column("away_score", sa.Integer(), nullable=False),
        sa.Column("home_team", sa.String(length=64), nullable=False),
        sa.Column("away_team", sa.String(length=64), nullable=False),
        sa.Column("match_done", sa.Boolean(), nullable=False),
        sa.Column("match_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("match", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_match_away_team"), ["away_team"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_match_home_team"), ["home_team"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_match_match_date"), ["match_date"], unique=False
        )

    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("isAdmin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "prediction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("predicted_home_score", sa.Integer(), nullable=False),
        sa.Column("predicted_away_score", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
            name="fk_prediction_match_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="fk_prediction_user_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prediction", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_prediction_match_id"), ["match_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_prediction_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prediction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prediction_user_id"))
        batch_op.drop_index(batch_op.f("ix_prediction_match_id"))

    op.drop_table("prediction")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))

    op.drop_table("user")
    with op.batch_alter_table("match", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_match_match_date"))
        batch_op.drop_index(batch_op.f("ix_match_home_team"))
        batch_op.drop_index(batch_op.f("ix_match_away_team"))

    op.drop_table("match")
    # ### end Alembic commands ###
