"""Added teams to db

Revision ID: b843bd24fd6b
Revises: 62bd53819d3e
Create Date: 2025-09-05 21:52:02.988466

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b843bd24fd6b"
down_revision = "62bd53819d3e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("logo_url", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("team", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_team_name"), ["name"], unique=True)

    with op.batch_alter_table("match", schema=None) as batch_op:
        batch_op.add_column(sa.Column("home_team_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("away_team_id", sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_match_away_team"))
        batch_op.drop_index(batch_op.f("ix_match_home_team"))
        batch_op.create_index(
            batch_op.f("ix_match_away_team_id"), ["away_team_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_match_home_team_id"), ["home_team_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_match_away_team_id",
            "team",
            ["away_team_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_match_home_team_id",
            "team",
            ["home_team_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("home_team")
        batch_op.drop_column("away_team")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("match", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("away_team", sa.VARCHAR(length=64), nullable=False)
        )
        batch_op.add_column(
            sa.Column("home_team", sa.VARCHAR(length=64), nullable=False)
        )
        batch_op.drop_constraint("fk_match_home_team_id", type_="foreignkey")
        batch_op.drop_constraint("fk_match_away_team_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_match_home_team_id"))
        batch_op.drop_index(batch_op.f("ix_match_away_team_id"))
        batch_op.create_index(
            batch_op.f("ix_match_home_team"), ["home_team"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_match_away_team"), ["away_team"], unique=False
        )
        batch_op.drop_column("away_team_id")
        batch_op.drop_column("home_team_id")

    with op.batch_alter_table("team", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_name"))

    op.drop_table("team")
    # ### end Alembic commands ###
