"""Added points earned

Revision ID: cb8184056e58
Revises: b843bd24fd6b
Create Date: 2025-09-16 20:23:48.241484

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb8184056e58"
down_revision = "b843bd24fd6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prediction", schema=None) as batch_op:
        batch_op.add_column(sa.Column("points_earned", sa.Integer(), nullable=False))
        batch_op.alter_column(
            "predicted_home_score", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "predicted_away_score", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prediction", schema=None) as batch_op:
        batch_op.alter_column(
            "predicted_away_score", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "predicted_home_score", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.drop_column("points_earned")

    # ### end Alembic commands ###
